image: ruby:2.5.3

variables:
  JEKYLL_ENV: development
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
    - 'echo baseurl: "/icsx5-website/" >>_config.yml'
    - 'echo url: "https://bitfireAT.gitlab.io" >>_config.yml'
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
