name: Build preview site
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
